import router from '@adonisjs/core/services/router'
import { middleware } from './kernel.js'

const UsersController = () => import('#controllers/users_controller')
const AuthController = () => import('#controllers/auth_controller')
const ContratosController = () => import('#controllers/contratos_controller')
const ContratoItemController = () => import('#controllers/contrato_item_controller')
const FaturamentosController = () => import('#controllers/faturamentos_controller')

// Registro, Login e Autenticação
router.post('/register', [AuthController, 'register']).as('auth.register')
router.post('/login', [AuthController, 'login']).as('auth.login')
router.delete('/logout', [AuthController, 'logout']).as('auth.logout').use(middleware.auth())
router.get('/me', [AuthController, 'me']).as('auth.me')
// Usuários
router.get('users', [UsersController, 'index'])
router.get('users/:id', [UsersController, 'show'])
router.post('users', [UsersController, 'store'])
router.put('users/:id', [UsersController, 'update'])
router.delete('users/:id', [UsersController, 'destroy'])
// Contratos
router.post('/contratos', [ContratosController, 'createContract'])
// .use(middleware.auth())
router.get('/contratos', [ContratosController, 'getContracts'])
// .use(middleware.auth())
router.get('/contratos/:id', [ContratosController, 'getContractById'])
// .use(middleware.auth())
router.put('/contratos/:id', [ContratosController, 'updateContract'])
// .use(middleware.auth())
router.delete('/contratos/:id', [ContratosController, 'deleteContract'])
// .use(middleware.auth())
// Itens de contratos
router.post('/contratos/:id/items', [ContratoItemController, 'createContractItem'])
// .use(middleware.auth())
router.get('/contratos/:id/items', [ContratoItemController, 'getContractItem'])
// .use(middleware.auth())
router.put('/contratos/items/:itemId', [ContratoItemController, 'updateContractItem'])
// .use(middleware.auth())
router.delete('/contratos/items/:itemId', [ContratoItemController, 'deleteContractItem'])
// .use(middleware.auth())
//Faturamentos
router.post('/contratos/:id/faturamentos', [FaturamentosController, 'createFaturamento'])
// .use(middleware.auth())
router.get('/faturamentos', [FaturamentosController, 'getFaturamentos'])
// .use(middleware.auth())
router.get('/faturamentos/:id', [FaturamentosController, 'getFaturamentoById'])
// .use(middleware.auth())
router.put('/faturamentos/:id', [FaturamentosController, 'updateFaturamento'])
// .use(middleware.auth())
router.delete('/faturamentos/:id', [FaturamentosController, 'deleteFaturamento'])
// .use(middleware.auth())
router.delete('/faturamentos/:id/items/:itemId', [FaturamentosController, 'deleteFaturamentoItem'])
// .use(middleware.auth())
router.post('/faturamentos/:id/items', [FaturamentosController, 'addFaturamentoItem'])
// .use(middleware.auth())
